apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configs.staticcontent.operators.openshift.io
spec:
  group: staticcontent.operators.openshift.io
  names:
    kind: Config
    listKind: ConfigList
    plural: configs
    singular: config
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Config is the Schema for the configs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ConfigSpec defines the desired state of Config
          properties:
            config:
              description: 'StaticConfig defines the desired state of Config TODO:
                Split to cloud specific configs'
              properties:
                identityAttrEmail:
                  description: identity provider config
                  type: string
                identityAttrID:
                  type: string
                identityAttrName:
                  type: string
                identityAttrPreferredUsername:
                  type: string
                identityBindName:
                  type: string
                identityMappingMethod:
                  type: string
                identityName:
                  type: string
                identityURL:
                  type: string
                osdLdapCA:
                  description: other configuration values
                  type: string
                telemeterServerURL:
                  type: string
                valeroOperatorImage:
                  type: string
              type: object
            platform:
              type: string
            syncDuration:
              description: A Duration represents the elapsed time between two instants
                as an int64 nanosecond count. The representation limits the largest
                representable duration to approximately 290 years.
              format: int64
              type: integer
          type: object
        status:
          description: ConfigStatus defines the observed state of Config
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
